// Generated by CoffeeScript 1.7.1
var Logger, config, daemon, fs, logger, path, startStopDaemon, _;

path = require('path');

startStopDaemon = require('start-stop-daemon');

Logger = require("./lib/logger");

logger = new Logger();

_ = require("lodash");

fs = require("fs");

config = require("nconf");

daemon = startStopDaemon({
  silent: false,
  max: 1000,
  watch: false,
  errFile: path.join(__dirname, 'log/forever.err')
}, function() {
  var Application;
  logger.info("----------- START -----------");
  Application = require("./lib/application");
  config.file({
    file: path.join(__dirname, "./config/config.json")
  });
  config.set("basepath", __dirname);
  return config.save((function(_this) {
    return function() {
      var application;
      application = new Application({
        "logger": logger,
        "config": config
      });
      return application.start();
    };
  })(this));
});

daemon.on("restart", function() {
  process.stdout.write('Restarting at ' + new Date() + '\n');
  return logger.info("----------- RESTART -----------");
});

daemon.on('exit', function() {
  process.stdout.write('index.js has exited after max restarts');
  return logger.info("----------- RESTART -----------");
});
