// Generated by CoffeeScript 1.7.1
var Logger, daemon, logger, path, startStopDaemon;

path = require('path');

startStopDaemon = require('start-stop-daemon');

Logger = require("./lib/logger");

logger = new Logger();

daemon = startStopDaemon({
  silent: false,
  max: 1000,
  watch: true,
  watchDirectory: __dirname,
  watchIgnoreDotFiles: true,
  watchIgnorePatterns: ["" + (path.resolve(__dirname, 'log')) + "/**"],
  errFile: path.resolve(__dirname, 'log/forever.err')
}, function() {
  var Application, application, config;
  logger.info("----------- START -----------");
  Application = require("./lib/application");
  config = require("./config");
  config.set("basePath", __dirname);
  application = new Application({
    "logger": logger,
    "config": config
  });
  return application.start();
});

daemon.on("restart", function() {
  process.stdout.write('Restarting at ' + new Date() + '\n');
  return logger.info("----------- RESTART -----------");
});

daemon.on('exit', function() {
  process.stdout.write('index.js has exited after max restarts');
  return logger.info("----------- RESTART -----------");
});
