// Generated by CoffeeScript 1.7.1
var daemon, path, startStopDaemon;

path = require('path');

startStopDaemon = require('start-stop-daemon');

daemon = startStopDaemon({
  silent: false,
  max: 1000,
  watch: true,
  watchDirectory: __dirname,
  watchIgnoreDotFiles: true,
  watchIgnorePatterns: ["" + (path.resolve(__dirname, 'log')) + "/**"],
  logFile: path.resolve(__dirname, 'log/forever.log'),
  errFile: path.resolve(__dirname, 'log/forever.err')
}, function() {
  var Application, Logger, application, config, logger;
  Logger = require("./lib/logger");
  logger = new Logger();
  logger.info("----------- START -----------");
  Application = require("./lib/application");
  config = require("./config");
  config.set("basePath", __dirname);
  application = new Application({
    "logger": logger,
    "config": config
  });
  return application.start();
});

daemon.on("restart", function() {
  return process.stdout.write('Restarting at ' + new Date() + '\n');
});

daemon.on('exit', function() {
  return process.stdout.write('index.js has exited after max restarts');
});
