// Generated by CoffeeScript 1.7.1
"use strict";
var Application, Socket, Sync, util;

Socket = require("./../eventhub-connector/socket-connector");

Sync = require("./../sync");

util = require("util");

Application = (function() {
  function Application(args) {
    this.logger = args.logger, this.config = args.config;
    this.eventHubConnector = new Socket({
      logger: this.logger,
      config: this.config
    });
    this.sync = new Sync({
      logger: this.logger,
      config: this.config
    });
  }

  Application.prototype.start = function() {
    this.initListeners();
    this.eventHubConnector.start();
    return this.sync.syncReset().then((function(_this) {
      return function() {
        return _this.sync.startAutoSync();
      };
    })(this));
  };

  Application.prototype.initListeners = function() {
    return this.eventHubConnector.on("command", (function(_this) {
      return function(command, callback) {
        return _this.sync.pushCommand(command).then(function(result) {
          return callback(null, result);
        })["catch"](function(err) {
          _this.logger.error(util.inspect(err, {
            depth: 30
          }));
          return callback(err);
        }).done();
      };
    })(this));
  };

  return Application;

})();

module.exports = Application;
