// Generated by CoffeeScript 1.7.1
"use strict";
var nconf, path;

nconf = require("nconf");

path = require("path");

nconf.argv().env().file({
  file: path.join(__dirname, "config.json")
});

module.exports = nconf;
