// Generated by CoffeeScript 1.7.1
"use strict";
var FS, Q, Rsync, Sync, async, events, exec, fs, path, request, util,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

FS = require("q-io/fs");

fs = require("fs-extra");

async = require("async-q");

Q = require("q");

path = require("path");

exec = require('child_process').exec;

events = require("events");

request = require("request");

util = require("util");

Rsync = require("rsync");

Sync = (function(_super) {
  __extends(Sync, _super);

  Sync.prototype.COMMANDS = {
    "sync-http": "syncHttp",
    "sync-backup": "syncGit",
    "sync-local": "syncLocal",
    "sync-reset": "syncReset"
  };

  function Sync(args) {
    this.config = args.config, this.logger = args.logger;
    this._source = this.config.get("folder:backup");
    this._dest = this.config.get("folder:dest");
    this._flags = {};
    this._gitUrl = this.config.get("git:url");
    this._gitDir = path.join(this._source, '.git');
    this._rsync = new Rsync({
      debug: true
    }).flags('avz').set('delete').exclude(this.config.get("syncIgnore"));
    this._queue = async.queue((function(_this) {
      return function(command) {
        var commandName;
        _this.logger.startTime("Command " + (util.inspect(command, {
          depth: 30
        })) + " processing");
        commandName = _this.COMMANDS[command.name];
        return _this[commandName](command).then(function() {
          return _this.logger.info(_this.logger.printTime("Command " + (util.inspect(command, {
            depth: 30
          })) + " processing"));
        });
      };
    })(this));
  }

  Sync.initFolders = function() {
    var args;
    args = Array.prototype.slice.call(arguments, 0);
    return async.each(args, function(file) {
      return FS.makeTree(file);
    });
  };

  Sync.prototype.updateFlagIndicators = function() {
    var flag, flags, indicators;
    indicators = this.config.get("indicator");
    flags = (function() {
      var _results;
      _results = [];
      for (flag in indicators) {
        _results.push(flag);
      }
      return _results;
    })();
    return async.each(flags, (function(_this) {
      return function(flag) {
        return FS.exists(path.join(_this._dest, indicators[flag])).then(function(result) {
          return _this._flags[flag] = result;
        });
      };
    })(this));
  };

  Sync.prototype.pushCommand = function(command) {
    this.logger.startTime("Command " + (util.inspect(command, {
      depth: 30
    })) + " in queue");
    return this._queue.push(command);
  };

  Sync.prototype._checkRepositoryStatus = function() {
    var deferred;
    this.logger.info("Start GIT status of '" + this._source + "'. Command: '" + (this._wrapGit("git status")) + "'");
    deferred = Q.defer();
    this.logger.startTime("GIT STATUS");
    this._execGit("git status", (function(_this) {
      return function(err, stdout, stderr) {
        _this.logger.info("GIT STATUS result: " + (stdout !== "" ? stdout : stderr) + (_this.logger.printTime("GIT STATUS")));
        if (stderr !== "") {
          return deferred.resolve("NOT_GIT");
        } else {
          return deferred.resolve("GIT");
        }
      };
    })(this));
    return deferred.promise;
  };

  Sync.prototype._cloneRepository = function() {
    var deferred;
    deferred = Q.defer();
    this.logger.info("Cleaning backup directory '" + this._source + "'");
    FS.removeTree(this._source).then((function(_this) {
      return function() {
        return FS.makeTree(_this._source);
      };
    })(this)).then((function(_this) {
      return function() {
        _this.logger.info("Start GIT CLONE. Clone '" + _this._gitUrl + "' into '" + _this._source + "'. Command: '" + (_this._wrapGit("git clone " + _this._gitUrl + " " + _this._source)) + "'");
        _this.logger.startTime("GIT CLONE");
        return _this._execGit("git clone " + _this._gitUrl + " " + _this._source, function(err, stdout, stderr) {
          _this.logger.info("GIT CLONE result: " + (stdout !== "" ? stdout : stderr) + (_this.logger.printTime("GIT CLONE")));
          if (err !== null) {
            return deferred.reject(err);
          } else {
            return deferred.resolve("SUCCESS");
          }
        });
      };
    })(this));
    return deferred.promise;
  };

  Sync.prototype._wrapGit = function(command) {
    return "GIT_SSH=" + (path.join(this.config.get("basePath"), this.config.get("git:sshShell"))) + " " + command;
  };

  Sync.prototype._execGit = function(command, callback) {
    return exec(this._wrapGit(command), {
      cwd: this._source,
      timeout: this.config.get("execTimeout")
    }, callback);
  };

  Sync.prototype._pullRepository = function() {
    var deferred;
    deferred = Q.defer();
    this.logger.info("Start GIT CLEAN. Command: '" + (this._wrapGit("git clean -xdf")) + "'");
    this.logger.startTime("GIT CLEAN");
    this._execGit("git clean -xdf", (function(_this) {
      return function(err, stdout, stderr) {
        _this.logger.info("GIT CLEAN result: " + (stdout !== "" ? stdout : stderr) + (_this.logger.printTime("GIT CLEAN")));
        if (err !== null) {
          return deferred.reject(err);
        }
        _this.logger.info("Start GIT RESET. Command: '" + (_this._wrapGit("git reset --hard origin/master")) + "'");
        _this.logger.startTime("GIT RESET");
        return _this._execGit("git reset --hard origin/master", function(err, stdout, stderr) {
          _this.logger.info("GIT RESET result: " + (stdout !== "" ? stdout : stderr) + (_this.logger.printTime("GIT RESET")));
          if (err !== null) {
            return deferred.reject(err);
          }
          _this.logger.info("Start GIT PULL. Command: '" + (_this._wrapGit("git pull --ff")) + "'");
          _this.logger.startTime("GIT PULL");
          return _this._execGit("git pull --ff", function(err, stdout, stderr) {
            _this.logger.info("GIT PULL result: " + (stdout !== "" ? stdout : stderr) + (_this.logger.printTime("GIT PULL")));
            if (err !== null) {
              return deferred.reject(err);
            }
            return deferred.resolve("SUCCESS");
          });
        });
      };
    })(this));
    return deferred.promise;
  };

  Sync.prototype.syncGit = function(command) {
    return Q.all([Sync.initFolders(this._source, this._dest), this.updateFlagIndicators()]).then((function(_this) {
      return function() {
        if (!_this._flags.stopContentDelivery) {
          return _this._checkRepositoryStatus().then(function(result) {
            if (result === "NOT_GIT") {
              return _this._cloneRepository();
            } else {
              return Q.resolve("SUCCESS");
            }
          }).then(function(result) {
            if (result === "SUCCESS") {
              return _this._pullRepository();
            } else {
              return Q.reject("FAIL");
            }
          }).then(function(result) {
            if (result === "SUCCESS") {
              return _this.syncLocal(command);
            } else {
              return Q.reject("FAIL");
            }
          });
        } else {
          _this.logger.info("Content delivery file was found.");
          return Q.resolve("Content delivery file was found.");
        }
      };
    })(this));
  };

  Sync.prototype.syncHttp = function(command) {
    this.logger.info("Start SYNC-HTTP.");
    this.logger.startTime("SYNC-HTTP");
    return Q.all([Sync.initFolders(this._source, this._dest), this.updateFlagIndicators()]).then((function(_this) {
      return function() {
        var changeSet, formUrl;
        if (!_this._flags.stopContentDelivery) {
          formUrl = "http://" + command.host + ":" + command.port;
          formUrl += "/" + (_this.config.get("client:customerId"));
          formUrl += "/" + (_this.config.get("client:hostId"));
          formUrl += "/" + (_this.config.get("client:contentRegion"));
          formUrl += "/" + command.snapshot.id;
          _this.logger.info("Constructed SYNC-HTTP fetch url: '" + formUrl + "'");
          changeSet = command.snapshot.changeSet;
          return Q.all([
            async.eachLimit(changeSet.added.concat(changeSet.modified), 5, function(changed) {
              var dirname, rQ, req, wQ, writeStream;
              wQ = Q.defer();
              dirname = path.dirname(path.join(_this._source, _this.config.get("client:contentRegion"), added));
              fs.mkdirpSync(dirname);
              writeStream = fs.createWriteStream(path.join(_this._source, _this.config.get("client:contentRegion"), added));
              writeStream.on("finish", function() {
                return wQ.resolve();
              });
              writeStream.on("close", function() {
                return wQ.reject();
              });
              rQ = Q.defer();
              _this.logger.info("Start Download '" + formUrl + changed + "'");
              _this.logger.startTime("Download " + changed);
              req = request("" + formUrl + changed).pipe(writeStream);
              req.on("end", function() {
                return rQ.resolve();
              });
              req.on("close", function() {
                return rQ.reject();
              });
              return Q.all([wQ, rQ]).then(function() {
                return this.logger.info("Download of " + changed + " is DONE. " + (this.logger.printTime("Download " + changed)));
              });
            }), async.eachLimit(changeSet.deleted, 5, function(deleted) {
              return FS.removeTree(path.join(_this._source, _this.config.get("client:contentRegion"), deleted));
            })
          ]);
        } else {
          _this.logger.info("Content delivery file is found.");
          return Q.resolve("Content delivery file is found.");
        }
      };
    })(this)).then((function(_this) {
      return function() {
        _this.logger.info("SYNC-HTTP is DONE. " + (_this.logger.printTime("SYNC-HTTP")));
        return _this.syncLocal(command);
      };
    })(this));
  };

  Sync.prototype.syncLocal = function(command) {
    var deferred;
    deferred = Q.defer();
    this.logger.info("Start LOCAL-SYNC. Rsync from '" + this._source + "' to '" + this._dest + "'.");
    this.logger.startTime("LOCAL-SYNC");
    Q.all([Sync.initFolders(this._source, this._dest), this.updateFlagIndicators()]).then((function(_this) {
      return function() {
        if (!_this._flags.stopContentDelivery) {
          _this._rsync.source(path.join(_this._source, _this.config.get("client:contentRegion") + "/")).destination(_this._dest);
          return _this._rsync.execute(function(err, resultCode) {
            var result;
            if (err) {
              deferred.reject(err);
            }
            result = resultCode === 0 ? "SUCCESS" : "FAIL";
            _this.logger.info("LOCAL-SYNC result: '" + result + "'. " + (_this.logger.printTime("LOCAL-SYNC")));
            return deferred.resolve(result);
          });
        } else {
          _this.logger.info("Content delivery file is found.");
          return deferred.resolve("Content delivery file is found.");
        }
      };
    })(this));
    return deferred.promise;
  };

  Sync.prototype._logChanges = function(result, key) {
    if (this._lastKey !== key) {
      this.logger.info("" + (key != null ? "" + key + " is found. " : "") + result);
      return this._lastKey = key;
    }
  };

  Sync.prototype.startAutoSync = function() {
    this.logger.info("Start AUTO-SYNC");
    if (this.intervalId == null) {
      return this.intervalId = setInterval((function(_this) {
        return function() {
          return _this._syncAuto();
        };
      })(this), 10000);
    }
  };

  Sync.prototype.stopAutoSync = function() {
    this.logger.info("Stop AUTO-SYNC");
    if (this.intervalId != null) {
      clearInterval(this.intervalId);
      return delete this.intervalId;
    }
  };

  Sync.prototype.syncReset = function() {
    var deferred;
    deferred = Q.defer();
    this.logger.startTime("SYNC-RESET started.");
    this.logger.startTime("SYNC-RESET");
    this.pushCommand({
      name: "sync-backup"
    }).then((function(_this) {
      return function(result) {
        return setTimeout(function() {
          return _this.pushCommand({
            name: "sync-backup"
          }).then(function(result) {
            _this.logger.info("SYNC-RESET is DONE. " + (_this.logger.printTime("SYNC-RESET")));
            return deferred.resolve(result);
          });
        }, 10000);
      };
    })(this));
    return deferred.promise;
  };

  Sync.prototype._syncAuto = function() {
    return this.updateFlagIndicators().then((function(_this) {
      return function() {
        if (_this._flags.stopContentDelivery) {
          return _this._logChanges('Content delivery stopped.', 'stopContentDelivery');
        } else {
          if (_this._lastKey === "stopContentDelivery") {
            _this._logChanges('Content delivery restarted.');
            return _this.syncReset();
          } else if (_this._flags.stopPeriodicRsync === true) {
            return _this._logChanges('Periodic LOCAL-SYNC stopped.', 'stopPeriodicRsync');
          } else {
            _this._logChanges('Periodic LOCAL-SYNC started.');
            return _this.pushCommand({
              name: "sync-local"
            });
          }
        }
      };
    })(this));
  };

  module.exports = Sync;

  return Sync;

})(events.EventEmitter);
