// Generated by CoffeeScript 1.7.1
"use strict";
var EventHubConnector, events,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

events = require("events");

EventHubConnector = (function(_super) {
  __extends(EventHubConnector, _super);

  function EventHubConnector() {
    return EventHubConnector.__super__.constructor.apply(this, arguments);
  }

  return EventHubConnector;

})(events.EventEmitter);

module.exports = EventHubConnector;
